### PR TITLE
B2BKing support (price groups & visibility)

### PR DESCRIPTION
**Pull request by mlstolk**
This update adds compatibility with the popular Woocommerce extension B2BKing (https://woocommerce-b2b-plugin.com/).
B2BKing offers customer-group pricing (min/max) and lets you set group-level product visibility. Both these functions did not work properly with the original Woo-product-table code. The modifications that allow the plugins to cooperate correctly are based on direct advice of the official support team and have been successfully tested.

### CODE REVIEW

**Comment by codersaiful** [comment]
I need your plugin to make compatible with our plugin.
I will make compatible with checking condition  your plugin installed or not.

I sent a mail to you over email. Please contact with me over email.

**Comment by codersaiful** [comment]
Dear sir, I have added your suggested code using our filter hook. Please check
https://github.com/codersaiful/woo-product-table/commit/b081beba2eedf600b9e42861524183c893758a0b

I have added following code:
```php
if( defined('B2BKINGCORE_DIR') && !function_exists( 'wpt_b2bking_plugin_integration' ) ){
    
    /**
     * Integration with B2BKing — Ultimate WooCommerce Wholesale and B2B Solution
     * plugin link: https://wordpress.org/plugins/b2bking-wholesale-for-woocommerce/
     * 
     * @since 3.0.2.0
     * @author Saiful Islam<codersaiful@gmail.com>
     * @author mlstolk https://github.com/mlstolk
     * @link https://github.com/codersaiful/woo-product-table/pull/136
     */
    function wpt_b2bking_plugin_integration( $args ){

        $user_id = get_current_user_id();
        $b2bking_plugin_enabled = (get_user_meta($user_id, 'b2bking_b2buser', true) === 'yes');
        
        $meta_query = $args['meta_query'];

        foreach( $meta_query as $w_key => $w_meta ){
            

            $find_key = array_search('_price', $w_meta);
            if( $find_key ){
                
                // set key to use for Minimum and Maximum price query 
                if ($b2bking_plugin_enabled){ //B2BKing
                    $b2bking_user_group = get_user_meta($user_id, 'b2bking_customergroup', true);
                    $query_price_key = 'b2bking_regular_product_price_group_'.$b2bking_user_group; 
                } else {
                    $query_price_key = '_price'; //default
                }

                $args['meta_query'][$w_key]['key'] = $query_price_key;

            }

        }


        /**
         * B2BKing: include only visible posts 
         * (set in B2BKing user settings on either group or user level)
         */
        if( $b2bking_plugin_enabled ){
            $b2bking_visible_ids = get_transient('b2bking_user_'.get_current_user_id().'_ajax_visibility');
            $b2bking_visible_ids = $args['post__in'] && is_array( $args['post__in'] ) ? array_intersect($args['post__in'], $b2bking_visible_ids): $b2bking_visible_ids;
            $args['post__in'] = $b2bking_visible_ids;
        }

        return $args;
    }
}
add_filter( 'wpto_table_query_args', 'wpt_b2bking_plugin_integration' );
```

**Comment by codersaiful** [comment]
Please check with your plugin with this following code.
Looking forward to hearing your response.
Thanks

**Comment by mlstolk** [comment]
Thank you for integrating this in a nicer way. However, the line you added
does not work because 'B2BKINGCORE_DIR' does not exist.
Everything works as expected when the condition is changed to:

if( defined('*B2BKING_DIR*') && !function_exists(
'wpt_b2bking_plugin_integration' ) ){



Op zo 7 nov. 2021 om 05:28 schreef Saiful Islam ***@***.***>:

**Comment by codersaiful** [comment]
Hello WebWizards, I got your mail to our support email. Ii would like to contact with you personally.
Actually, If anyone wants to make his plugin compatible with woo product table.  Need to use our available filter. 

Can you try to fix it here? 
https://github.com/codersaiful/woo-product-table/blob/72f97836b4f59ac31658e9e8950610a9f1833707/includes/functions.php#L1616

Please install our latest version from github and fix it based on your requirements.
And let me know.with making plugins compatible

**Comment by codersaiful** [comment]
One things, I would like to confirm that, i just put your code over there using filter hook. Nothing else.

**Comment by codersaiful** [comment]
https://github.com/codersaiful/woo-product-table/pull/143/commits/e29c468a600c379ebe040622944c17f5d20f0018 Check this commit. I have added your code.
https://github.com/codersaiful/woo-product-table/blob/79363c4e7cead0039eade1ce4e3f07f6402929ae/includes/functions.php#L1616

```php
if( defined('B2BKINGCORE_DIR') && !function_exists( 'wpt_b2bking_plugin_integration' ) ){
    
    /**
     * Integration with B2BKing — Ultimate WooCommerce Wholesale and B2B Solution
     * plugin link: https://wordpress.org/plugins/b2bking-wholesale-for-woocommerce/
     * 
     * @since 3.0.2.0
     * @author Saiful Islam<codersaiful@gmail.com>
     * @author mlstolk https://github.com/mlstolk
     * @link https://github.com/codersaiful/woo-product-table/pull/136
     */
    function wpt_b2bking_plugin_integration( $args ){

        $user_id = get_current_user_id();

        // if b2bking visibility is enabled
        if (intval(get_option( 'b2bking_all_products_visible_all_users_setting', 1 )) !== 1){
            if (intval(get_option('b2bking_disable_visibility_setting', 0)) === 0){

                // set products to visible b2bking products (at group or user level)
                $b2bking_visible_ids = get_transient('b2bking_user_'.$user_id.'_ajax_visibility');
                $b2bking_visible_ids = $args['post__in'] && is_array( $args['post__in'] ) ? array_intersect($args['post__in'], $b2bking_visible_ids): $b2bking_visible_ids;
                $args['post__in'] = $b2bking_visible_ids;
            }
        }

        return $args;
    }

    add_filter( 'wpto_table_query_args', 'wpt_b2bking_plugin_integration' );
}
```

**Comment by codersaiful** [comment]
Is this perfect? please check and let me know details.
Thanks

**Comment by mlstolk** [comment]
As I mentioned before **B2BKINGCORE_DIR** does not exist anywhere in the code base of B2B King. So this code does not work because of the if statement on line 1616.
If it is replaced by **B2BKING_DIR** (which is indeed defined in b2bking.php line 21), everything works as it should.

**Comment by codersaiful** [comment]
Updated.
https://github.com/codersaiful/woo-product-table/pull/144/commits/0e773b2549daf5cbc7b3f577335b38eac5aca1cb
Please check

**Comment by codersaiful** [comment]
https://github.com/codersaiful/woo-product-table/blob/584a5df3ed5940dbe10e37f877dfabea940f8d6d/includes/functions.php#L1616

**Comment by mlstolk** [comment]
Now, this works perfectly!

**Comment by codersaiful** [comment]
Thanks for confirmation. This snippet will be available in wp org in next update

**Comment by mlstolk** [comment]
An addition to my previous remark: now, the part activates correctly and the correct visibility (and prices) show.
However, I am missing the lines to filter the minimum and maximum prices that was in my original code.

The part that with the comment "set key to use for Minimum and Maximum price query" which sets $query_price_key is gone in your latest modifications.

**Pull request closed without merging**
